name: Build, Test & Release on Push

on:
  push:
    branches:
      - main
jobs:
  build:
    uses: khumozin/workflow-templates/.github/workflows/angular-build-app.yml@1.4.0
    with:
      node_version: "['20.x']"

  dependency-analysis:
    uses: khumozin/workflow-templates/.github/workflows/nodejs-dependency-analysis.yml@1.3.0
    with:
      node_version: "['20.x']"
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}

  secret-scan:
    uses: khumozin/workflow-templates/.github/workflows/secret-scan.yml@1.1.0
    secrets:
      gitguardian_api_key: ${{ secrets.GITGUARDIAN_API_KEY }}

  unit-test:
    needs: [build, dependency-analysis, secret-scan]
    uses: khumozin/workflow-templates/.github/workflows/angular-unit-test-app.yml@1.4.0
    with:
      node_version: "['20.x']"

  e2e-test:
    needs: [build, dependency-analysis, secret-scan]
    uses: khumozin/workflow-templates/.github/workflows/angular-cypress-e2e-test-app.yml@1.4.0
    with:
      node_version: "['20.x']"

  semantic-release:
    needs: [unit-test, e2e-test]
    uses: khumozin/workflow-templates/.github/workflows/nodejs-semantic-release.yml@1.4.0
    with:
      node_version: "['20.x']"
    permissions:
      contents: write

  image-build:
    needs: [semantic-release]
    if: ${{ needs.semantic-release.outputs.pkg-version != needs.semantic-release.outputs.prev-pkg-version }}
    uses: khumozin/workflow-templates/.github/workflows/docker-build-and-publish.yml@1.4.0
    with:
      image_name: news-app
      tag: ${{ needs.semantic-release.outputs.pkg-version }}
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}

  update-manifests:
    runs-on: ubuntu-latest
    needs: [image-build, semantic-release]
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: khumozin/news-app-gitops
          ref: main
          token: ${{ secrets.NEWSAPP_PAT }}

      - name: GitOps - Update Deployment Manifest
        run: |
          cd dev
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/news-app:v${{ needs.semantic-release.outputs.pkg-version }}|" deployment.yml

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dev/deployment.yml
          git commit -m "chore: bump image version to v${{ needs.semantic-release.outputs.pkg-version }}"
          git push
