name: Build, Test & Release on Push

on:
  push:
    branches:
      - main
jobs:
  angular:
    uses: khumozin/workflow-templates/.github/workflows/angular-build-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  snyk:
    uses: khumozin/workflow-templates/.github/workflows/nodejs-dependency-analysis.yml@1.5.0
    with:
      node_version: "['20.x']"
    secrets: inherit

  sonar-cloud:
    uses: khumozin/workflow-templates/.github/workflows/sonar-cloud-static-code-analysis.yml@1.5.5
    with:
      project_base_directory: news-app
      source_folder: "src/"
    secrets: inherit

  gitguardian:
    uses: khumozin/workflow-templates/.github/workflows/gitguardian-secret-scan.yml@1.5.0
    secrets: inherit

  jasmine:
    needs: [angular, snyk, gitguardian, sonar-cloud]
    uses: khumozin/workflow-templates/.github/workflows/angular-unit-test-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  cypress:
    needs: [angular, snyk, gitguardian, sonar-cloud]
    uses: khumozin/workflow-templates/.github/workflows/angular-cypress-e2e-test-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  semantic-release:
    needs: [jasmine, cypress]
    uses: khumozin/workflow-templates/.github/workflows/nodejs-semantic-release.yml@1.5.0
    with:
      node_version: "['20.x']"
    permissions:
      contents: write

  docker:
    needs: [semantic-release]
    if: ${{ needs.semantic-release.outputs.pkg-version != needs.semantic-release.outputs.prev-pkg-version }}
    uses: khumozin/workflow-templates/.github/workflows/docker-buildx-scan-and-publish.yml@1.8.2
    with:
      image_name: news-app
      tag: ${{ fromJson(needs.semantic-release.outputs.pkg-version) }}
    secrets: inherit

  update-manifests:
    runs-on: ubuntu-latest
    needs: [docker, semantic-release]
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: khumozin/news-app-gitops
          ref: main
          token: ${{ secrets.NEWSAPP_PAT }}

      - name: GitOps - Update Deployment Manifest
        run: |
          cd dev
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/news-app:v${{ needs.semantic-release.outputs.pkg-version }}|" deployment.yml

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dev/deployment.yml
          git commit -m "chore: bump image version to v${{ needs.semantic-release.outputs.pkg-version }}"
          git push
