name: Lint, Build & Test on Pull Request

on:
  pull_request:
    branches:
      - main
jobs:
  eslint:
    uses: khumozin/workflow-templates/.github/workflows/angular-lint-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  gitguardian:
    uses: khumozin/workflow-templates/.github/workflows/gitguardian-secret-scan.yml@1.5.0
    secrets: inherit

  snyk:
    uses: khumozin/workflow-templates/.github/workflows/nodejs-dependency-analysis.yml@1.5.0
    with:
      node_version: "['20.x']"
    secrets: inherit

  sonar-cloud:
    uses: khumozin/workflow-templates/.github/workflows/sonar-cloud-static-code-analysis.yml@1.5.0
    with:
      project_base_directory: news-app
      source_folder: "src/"
    secrets: inherit

  angular:
    needs: [eslint, gitguardian, snyk, sonar-cloud]
    uses: khumozin/workflow-templates/.github/workflows/angular-build-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  jasmine:
    needs: [angular]
    uses: khumozin/workflow-templates/.github/workflows/angular-unit-test-app.yml@1.5.0
    with:
      node_version: "['20.x']"

  cypress:
    needs: [angular]
    uses: khumozin/workflow-templates/.github/workflows/angular-cypress-e2e-test-app.yml@1.5.0
    with:
      node_version: "['20.x']"
