name: Lint, Build & Test on Pull Request

on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: khumozin/workflow-templates/.github/workflows/angular-lint-app.yml@1.2.1
    with:
      node_version: "['20.x']"

  secret-scan:
    uses: khumozin/workflow-templates/.github/workflows/secret-scan.yml@1.2.1
    secrets:
      gitguardian_api_key: ${{ secrets.GITGUARDIAN_API_KEY }}

  dependency-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

    #   - name: Run npm audit
    #     run: npm audit --audit-level=high

  build:
    needs: [lint, secret-scan, dependency-analysis]
    uses: khumozin/workflow-templates/.github/workflows/angular-build-app.yml@1.2.1
    with:
      node_version: "['20.x']"

  unit-test:
    needs: [build]
    uses: khumozin/workflow-templates/.github/workflows/angular-unit-test-app.yml@1.2.1
    with:
      node_version: "['20.x']"

  e2e-test:
    needs: [build]
    uses: khumozin/workflow-templates/.github/workflows/angular-cypress-e2e-test-app.yml@1.2.1
    with:
      node_version: "['20.x']"
